/**
 * Copyright © 2009 HERA Consulting Ltd.  
 */

package com.gnugu.secretbox.tests;

import javax.crypto.BadPaddingException;

import junit.framework.Assert;
import android.test.AndroidTestCase;
import com.gnugu.secretbox.Crypto;

/**
 * Tests for Crypto.
 * 
 * @author HERA Consulting Ltd.
 *
 */
public class CryptoTest extends AndroidTestCase {

	private static void doEncryptDecrypt(Crypto cr, String original) throws BadPaddingException {
		byte[] encrypted = cr.encrypt(original);
		String decrypted = cr.decryptToString(encrypted);
		
		Assert.assertEquals(original, decrypted);
	}
	
	public void testRoundTrip() throws BadPaddingException {
		doEncryptDecrypt(new Crypto("blah", Crypto.generateSalt()),
				"this is the original string");
	}

	public void testAutoGeneratedKeyRoundTrip() throws BadPaddingException {
		doEncryptDecrypt(new Crypto(Crypto.generateKey()),
				"this is the original string");
	}
	
	public void testEmptyString() throws BadPaddingException {
		doEncryptDecrypt(new Crypto("blah", Crypto.generateSalt()),
				"");
	}
	
	
}
